### PR TITLE
Move to use Buildkite for CI

### PR DESCRIPTION
**Pull request by boydgreenfield**
For discussion. This moves from CircleCI to [Buildkite](https://buildkite.com/onecodex/onecodex) for CI. This lets us manage our own secrets, store artifacts, etc. (Buildkite is just the coordinating API). It also allows us to quickly elastically scale workers:

image

Some obvious further improvements:
- [ ] Use [ECR Cache plugin](https://github.com/seek-oss/docker-ecr-cache-buildkite-plugin) and a base Docker image to greatly speed up test requirements installs _or_ [this caching plugin](https://github.com/danthorpe/cache-buildkite-plugin)
- [ ] Additional Python version tests (potentially scheduled vs. on every commit)

### CODE REVIEW

**Comment by boydgreenfield** [comment]
**Testing speed note:** _Without_ any caching, we're at 3m23s for tests vs. 2m29s on CircleCI _with caching_:

image

image

**Comment by bovee** [comment]
Just to understand, the advantage here is test speed? Or its secrets management is better?

**Comment by boydgreenfield** [comment]
> Just to understand, the advantage here is test speed? Or its secrets management is better?

Let's discuss live. The advantages on this repo specifically are fairly minor, this was just a convenient place to test Buildkite.

**Comment by boydgreenfield** [comment]
We moved to GH Actions instead.

**Pull request closed without merging**
