### PR TITLE
Test on python 3.9

### PR DESCRIPTION
**Pull request by Keats**
## Status
- [x] **Ready**

## Description
Also drop python 3.6 as it's EOL at the end of the year

### CODE REVIEW

**Review by jairideout — APPROVED** [review]

**Comment by jairideout** [comment]
Looks like the test matrix is still expecting 3.6 results for macOS & Linux?

**Comment by Keats** [comment]
I believe it's a bug in GH actions, we ran into the same one for chrononaut

**Comment by jairideout** [comment]
Weird... we can't merge the PR because those two statuses are required. Maybe try closing and reopening the PR?

**Comment by Keats** [comment]
I can as an admin. @pkonieczny even had issues on a subsequent PR, it's really odd.

**Pull request merged**
